#!/bin/bash
set -e

DIR_NAME="bash_demo"
FILE_NAME="demo.txt"
mkdir -p "$DIR_NAME"
cd "$DIR_NAME"
echo "This file was created on: $(date)" > "$FILE_NAME"
echo "Demo file generated by create_demo.sh" >> "$FILE_NAME"
echo "----- Contents of $FILE_NAME -----"
cat "$FILE_NAME"
echo "-----------------------------------"